# go-makefiles example Makefile for "auto" feature

# Specify root package name and configure binaries
GO_ROOT_PACKAGE_NAME=github.com/anexia-it/go-makefiles/examples/auto

# Configure AUTO_ variables
AUTO_ENABLE_BINARIES=1
AUTO_ENABLE_TEST=1
AUTO_ENABLE_BENCHMARK=1
AUTO_ENABLE_GOFMT=1
AUTO_ENABLE_GOIMPORTS=1
AUTO_ENABLE_GENERATE=1

# Include auto.mk - done
include ../../auto.mk
